import Foundation

/// Persists user settings and generates the .env file for Docker Compose.
class Config {
    static let shared = Config()

    // MARK: - Settings

    var httpPort: Int = 7545
    var p2pPort: Int = 7546
    var publicURL: String = "http://localhost:7545"
    var postgresPassword: String = "changeme"
    var autoStartOnLaunch: Bool = false
    var autoStartOnLogin: Bool = false

    // Advanced
    var chainRpcURL: String = ""
    var contractNodeStaking: String = ""
    var operatorPrivateKey: String = ""
    var tigrisBucket: String = ""
    var autoSync: Bool = false
    /// Owner-only push. Persisted as a setting rather than read from a hand-edited
    /// `.env`, because `writeEnvFile()` regenerates that file on every start and
    /// would discard the edit. Matches the node's own default; set false only for a
    /// rolling upgrade whose pushers are not yet the repo owner.
    var enforceOwnerPush: Bool = true
    var repoPathString: String = ""

    // MARK: - Paths

    /// Path to the gitlawb-node repo clone (for local builds).
    var repoPath: URL {
        if !repoPathString.isEmpty {
            return URL(fileURLWithPath: repoPathString)
        }
        // Use compile-time source path to find the repo root.
        // #filePath = .../gitlawb-node/macos-app/Sources/GitlawbNode/Config.swift
        // repo root = 4 directories up from the source file
        let sourceFile = URL(fileURLWithPath: #filePath)
        let repoRoot = sourceFile
            .deletingLastPathComponent() // Sources/GitlawbNode/
            .deletingLastPathComponent() // Sources/
            .deletingLastPathComponent() // macos-app/
            .deletingLastPathComponent() // gitlawb-node/
        let compose = repoRoot.appendingPathComponent("docker-compose.yml")
        let dockerfile = repoRoot.appendingPathComponent("Dockerfile")
        if FileManager.default.fileExists(atPath: compose.path) &&
           FileManager.default.fileExists(atPath: dockerfile.path) {
            return repoRoot
        }
        return dataDirectory
    }

    var dataDirectory: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        return appSupport.appendingPathComponent("GitlawbNode")
    }

    private var configFilePath: URL {
        dataDirectory.appendingPathComponent("config.json")
    }

    // MARK: - Init

    private init() {
        load()
    }

    // MARK: - Persistence

    func persist() {
        let dict: [String: Any] = [
            "httpPort": httpPort,
            "p2pPort": p2pPort,
            "publicURL": publicURL,
            "postgresPassword": postgresPassword,
            "autoStartOnLaunch": autoStartOnLaunch,
            "autoStartOnLogin": autoStartOnLogin,
            "chainRpcURL": chainRpcURL,
            "contractNodeStaking": contractNodeStaking,
            "operatorPrivateKey": operatorPrivateKey,
            "tigrisBucket": tigrisBucket,
            "autoSync": autoSync,
            "enforceOwnerPush": enforceOwnerPush,
            "repoPath": repoPathString,
        ]

        do {
            try FileManager.default.createDirectory(at: dataDirectory, withIntermediateDirectories: true)
            let data = try JSONSerialization.data(withJSONObject: dict, options: [.prettyPrinted, .sortedKeys])
            try data.write(to: configFilePath, options: .atomic)
        } catch {
            // Non-fatal — settings won't persist across restarts
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: configFilePath),
              let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return
        }

        httpPort = dict["httpPort"] as? Int ?? httpPort
        p2pPort = dict["p2pPort"] as? Int ?? p2pPort
        publicURL = dict["publicURL"] as? String ?? publicURL
        postgresPassword = dict["postgresPassword"] as? String ?? postgresPassword
        autoStartOnLaunch = dict["autoStartOnLaunch"] as? Bool ?? autoStartOnLaunch
        autoStartOnLogin = dict["autoStartOnLogin"] as? Bool ?? autoStartOnLogin
        chainRpcURL = dict["chainRpcURL"] as? String ?? chainRpcURL
        contractNodeStaking = dict["contractNodeStaking"] as? String ?? contractNodeStaking
        operatorPrivateKey = dict["operatorPrivateKey"] as? String ?? operatorPrivateKey
        tigrisBucket = dict["tigrisBucket"] as? String ?? tigrisBucket
        autoSync = dict["autoSync"] as? Bool ?? autoSync
        enforceOwnerPush = dict["enforceOwnerPush"] as? Bool ?? enforceOwnerPush
        repoPathString = dict["repoPath"] as? String ?? repoPathString
    }

    // MARK: - .env File Generation

    /// Writes the .env file that Docker Compose reads.
    func writeEnvFile() {
        let envPath = dataDirectory.appendingPathComponent(".env")

        var lines = [String]()
        lines.append("# Generated by Gitlawb Node app — do not edit manually")
        lines.append("POSTGRES_PASSWORD=\(postgresPassword)")
        lines.append("GITLAWB_PUBLIC_URL=\(publicURL)")
        lines.append("GITLAWB_PORT=\(httpPort)")
        lines.append("GITLAWB_P2P_PORT=\(p2pPort)")
        lines.append("GITLAWB_AUTO_SYNC=\(autoSync)")
        lines.append("GITLAWB_ENFORCE_OWNER_PUSH=\(enforceOwnerPush)")

        if !chainRpcURL.isEmpty {
            lines.append("GITLAWB_CHAIN_RPC_URL=\(chainRpcURL)")
        }
        if !contractNodeStaking.isEmpty {
            lines.append("GITLAWB_CONTRACT_NODE_STAKING=\(contractNodeStaking)")
        }
        if !operatorPrivateKey.isEmpty {
            lines.append("GITLAWB_OPERATOR_PRIVATE_KEY=\(operatorPrivateKey)")
        }
        if !tigrisBucket.isEmpty {
            lines.append("GITLAWB_TIGRIS_BUCKET=\(tigrisBucket)")
        }

        lines.append("") // trailing newline

        let content = lines.joined(separator: "\n")

        do {
            try FileManager.default.createDirectory(at: dataDirectory, withIntermediateDirectories: true)
            try content.write(to: envPath, atomically: true, encoding: .utf8)
        } catch {
            // Non-fatal
        }
    }
}
